name: Dotnet Library Build

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: dotnet version to use (defaults to 6.0.x)
        required: false
        type: string
        default: '6.0.x'
      publishable:
        description: Whether packages should be deployed to Nuget server
        type: boolean
        # default: ${{ github.ref_name == 'develop' || github.ref_name == 'master' || endsWith(github.ref_name, '.x') || endsWith(github.ref_name, '-workflow') }}
        default: false
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print environment versions
        run: |
          NPM_V=$(npm -v)
          echo npm version':' $NPM_V
          DOTNET_CLI_V=$(dotnet --version)
          echo dotnet cli version':' $DOTNET_CLI_V
          echo dotnet input version':' ${{ inputs.dotnet-version }}
          echo "::notice::dotnet cli version 2 $DOTNET_CLI_V"
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true
          SKETCH7_NUGET_API_KEY: ${{secrets.NUGET_KEY}}

      - name: dotnet restore
        run: dotnet restore

      - name: dotnet build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: npm test

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: all-package
          retention-days: 1
          path: 
            /home/runner/work/**/bin/**/*

      - name: Print PUBLISH
        run: echo "Is publishable ${{ inputs.publishable }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: inputs.publishable
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          name: all-package # optional else it will download all artifacts.

      - name: Print version
        run: echo "::notice::Package version ${{ github.env.VERSION }}"
        
        # todo: publish instead
        
      # - name: Publish NuGet
      #   run: |
      #     npm run publish:dev