name: dotnet package build/publish

on:
  workflow_call:
    inputs:
      dotnet-version:
        description: dotnet version to use (defaults to 6.0.x)
        required: false
        type: string
        default: '6.0.x'
      publishable:
        description: Determines whether packages should be published to Nuget
        type: boolean
        default: ${{ contains(fromJSON('["develop", "master", "workflow"]'), github.ref_name) || endsWith(github.ref_name, '.x')  }}
        required: false
      source-url:
        description: Default nuget source url
        type: string
        default: 'https://api.nuget.org/v3/index.json'
        required: false
    secrets:
      nuget-auth-token:
        description: Auth token for Nuget
        required: false
    outputs:
      version:
        description: "Version of the package"
        value: ${{ jobs.publish.outputs.version }}

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_AUTH_TOKEN: ${{ secrets.nuget-auth-token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print environment versions
        run: |
          NPM_V=$(npm -v)
          echo npm version':' $NPM_V
          DOTNET_CLI_V=$(dotnet --version)
          echo dotnet cli version':' $DOTNET_CLI_V
          echo dotnet input version':' ${{ inputs.dotnet-version }}
          echo "::notice::dotnet cli version 2 $DOTNET_CLI_V"
          echo github ref_name: ${{ github.ref_name }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          source-url: ${{ inputs.source-url }}

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: npm test

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: all-package
          retention-days: 1
          path:
            /home/runner/work/**/bin/**/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: inputs.publishable
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          source-url: ${{ inputs.source-url }}

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        with:
          name: all-package # optional else it will download all artifacts.

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Build version
        id: version-builder
        if: inputs.publishable
        uses: sketch7/version-builder-action@main
        with:
          preid-branches: "master,refs/heads/feature/reusable-workflow" # todo: remove and use default
          # preid: "rc"

      - name: Set version envs
        run: |
          echo "VERSION=${{ steps.version-builder.outputs.version }}" >> $GITHUB_ENV
          echo "ASSEMBLY_VERSION=${{ steps.version-builder.outputs.nonSemverVersion }}" >> $GITHUB_ENV

      # - name: Print version $V
      #   run: echo "::notice::Package version $VERSION"
      # - name: Print version env.v
      #   run: echo "::notice::Package version ${{env.VERSION}}}}"

      - name: Pack
        run: dotnet pack -p:PackageVersion=$VERSION -p:AssemblyVersion=$ASSEMBLY_VERSION -o ./ -c release --include-symbols -p:SymbolPackageFormat=snupkg

      - name: Publish
        run: dotnet nuget push "*.nupkg" -k $NUGET_AUTH_TOKEN -s ${{ inputs.source-url }} --skip-duplicate

      - name: Git tag
        run: |
          git tag $VERSION
          git push --tags

    outputs:
      version: ${{ steps.version-builder.outputs.version }}
